apiVersion: v1
kind: ConfigMap
metadata:
  name: devsu-nodejs-config
data:
  NODE_ENV: "production"
  PORT: "8000"
  DATABASE_NAME: "/app/data/dev.sqlite"
---

apiVersion: v1
kind: Secret
metadata:
  name: devsu-nodejs-secret
type: Opaque
stringData:
  DATABASE_USER: "user"
  DATABASE_PASSWORD: "password"
